### ISSUE TITLE
Schematic TODO

### ISSUE THREAD

**Issue by Alan-JH** [Alan-JH/TJ-EPS#4]
- [x] Implement solar panel telemetry on separable module
- [x] Implement telemetry ADC and controls
- [x] Implement bus reset timer
- [x] Implement overcurrent retry timer
- [x] Implement STM32 Watchdog timer
- [x] Implement USB charge to MPPT4 with LTC4412
- [x] Refine component selection for Buck and Boost controllers in PCM
- [x] Make cell protections separable
- [x] Add sheet comments
- [x] Redundant capacitors (specify in component selection)
